
try:

except Exception as ex:
    print(f"error information:{ex}")
finally:
    print("exit")